# Generated by Django 4.1.2 on 2022-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, null=True, upload_to='markalar/')),
                ('isim', models.CharField(max_length=300)),
            ],
        ),
    ]
