# Generated by Django 4.1.2 on 2022-11-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_altkategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='urunler.altkategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='urunler.altkategori'),
        ),
    ]
