# Generated by Django 4.1.2 on 2022-11-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_urun_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.marka'),
        ),
    ]
